name: FGO Login System

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    steps:
    
      - name: Gettings files from Repo
        uses: actions/checkout@v4
        
      - name: Install Requeriments
        run: |
          pip install -r requirements.txt

      - name: Execute main script 1
        run: |
          python3 main.py
        env:
          userIds: ${{ secrets.GAME_USERIDS }}
          authKeys: ${{ secrets.GAME_AUTHKEYS }}
          secretKeys: ${{ secrets.GAME_SECRETKEYS }}
          tgBotToken: ${{ secrets.TGBOTTOKEN }}
          tgChatID: ${{ secrets.TGCHATID }}
          userFlags: ${{ secrets.USERFLAGS }}
          DEVICE_INFO_SECRET: ${{ secrets.DEVICE_INFO_SECRET }}
          APP_CHECK_SECRET: ${{ secrets.APP_CHECK_SECRET }}
          USER_AGENT_SECRET_2: ${{ secrets.USER_AGENT_SECRET_2 }}
